name = "TelegramMessageParser"
uuid = "cf04f27f-8d91-4d5e-9f0b-6c05761bcbb8"
authors = ["lassepe <lasse.peters@mailbox.org>"]
version = "0.2.1"

[deps]
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"

[compat]
Cascadia = "0.4, 0.5, 1"
DocStringExtensions = "0.8"
Gumbo = "0.8"
julia = "1.4"
